### ISSUE TITLE
When selecting ISO shows error, then iso filesystem corrupted

### ISSUE THREAD

**Issue by TheMorc** [kamilion/customizer-qt5#10]
Hello,
I tried Customizer on Ubuntu 14.04 64bit with Customizer 4.1.1
I used ubuntu-mini-remix-14.04-i386.iso.
In gui i clicked Select ISO, then i selected it and this error showed up: 
![screenshot from 2016-09-18 13 38 38](https://cloud.githubusercontent.com/assets/13377926/18615358/4934f7d4-7da5-11e6-842c-4534cde739cd.png)
i clicked ok then warning showed up: 
![screenshot from 2016-09-18 13 39 51](https://cloud.githubusercontent.com/assets/13377926/18615361/657aed36-7da5-11e6-8af8-cc1e216533fe.png)

i dont know what happened is this because i have Ubuntu in Slovak language and not in English?

**Comment by MorcCrafak** [comment]
on old fork i read i cannot edit 32bit on 64 and vice versa so that means this is fixed, i will try to download 64bit.

**Comment by MorcCrafak** [comment]
FIXED!
the problem was in folder name "Stiahnuté"
that "é" letter was doing problems

**Comment by kamilion** [comment]
This issue will be fixed in a future revision of customizer with python3 support -- we should no longer encounter unicode issues. This forked repository is going away, and will be replaced with the official one.
If you still encounter issues after the python3 default being changed; please file another issue.
