### ISSUE TITLE
Incompatible changes and duplicates

### ISSUE THREAD

**Issue by clearkimura** [kamilion/customizer-qt5#14]
Due to recent makeover of official fork, source code from "old stable" is now cloned to `master` branch of official fork for some unexplained reason (other than fork maintainer intention to send pull request for supporting PyQt5).

As a result, existing source code in official fork has now created:

* duplicate script of "old stable" in `INSTALL`
* duplicate program version of "old stable" in `Makefile`, `CHANGELOG`
* duplicate package version of "old stable" in `debian/changelog`
* duplicate documentation of "old stable" in `docs/`
* duplicate releases of "old stable" in GitHub releases

In addition to:

* duplicate Wiki that has been remain *unfixed* since the project was forked in early 2016

Questions to answer:

* was "option D" misunderstood as recalled in #2 in early 2016?
* why official fork has made a U-turn to clone incompatible changes from "old stable"?
* where is the development plan of official fork?

Kindly explain and justify.

**Comment by kamilion** [comment]
I had some time off (23rd-27th) for my birthday on the 29th; so I figured I could catch up on some development.

Most of my time is spent maintaining an operating system distro for other people to use.
"Hey, I can shave a hundred megs off the image by dropping QT4 now that qt5.8 and qt lite are here!"

The only thing that made this an 'official' fork was me responding to https://github.com/clearkimura/Customizer/issues/70 which to my understanding was the current maintainer stepping down and preparing to leave the project to someone else to continue development on. I volunteered because I used the project and understood it. 

Since the 'stable' repo was not stable but constantly updating in my absence, making releases 4.1.2, 4.1.3, and 4.1.4 on it's own, I decided it was time to un-diverge the repos and rebase my patches on the much improved, cleaned up stable sources with better spelling, makefile improvements, and what appeared to be a working debian package generation routine.

It would have been cleaner for me to continue my patchset from the improved code; as github refused to allow me to cleanly merge the stable repo on top of mine, I had to move my local repo out of the way, clone a new copy from stable, and spend an hour improving and reworking my patches on top of it, intending on the new patchset to stable to be the canonical version that was to be developed going forward.

I spent extra time and effort making sure the patchset would apply to stable, changed my goofy memey variable names, made responsible commitlog entries instead of "I accidentally QT5'd", and went out of my way to assure all the changes that someone would need to enable the PyQt5 support was documented.

In response, I get passive aggressivity and bulletpoints.
This is the kind of behavior that makes me refuse to work in corporate environments.

Now, my chest hurts, I don't feel 'clean', and I feel like I'm being the asshole kid who takes his ball and goes home in the middle of a game at the park.

In this state; I no longer want to develop, I don't even really want to look at a computer.

So now I've changed my plans and I'm going to go away for the weekend.

But unlike the asshole kid taking his ball with him; I'm just going to scribble my name on it and hope someone leaves it by my front door before sundown. Everything that was in my repo is now in the self descriptive branch 'my-shitty-patches', the work I put into bringing QT5 support to customizer is in 'qt5' against the upstream master.

If I feel better after taking a weekend off perhaps my decision to shutter will change.

**Comment by clearkimura** [comment]
Hm... I have lost my words to reply elsewhere. The responses change too fast and difficult to follow by me. Updated information posted by fork maintainers are scattered all over the repositories and issues.

Self-replied after quoted text.

> was "option D" misunderstood as recalled in #2 in early 2016?

Since "option D" was agreed upon, @clearkimura expected development at official fork will be independent, regardless of "old stable" will be abandoned or still undergoes changes for trivial clean up.

Therefore, even "old stable" were to undergo changes, it was *never* intended to move away from Python 2.7 and PyQt and it were to remain relevant at least until 2019, being "old stable" for end users, whilst official fork development may face new issues upon migration.


> why official fork has made a U-turn to clone incompatible changes from "old stable"?

There was no reason for official fork to incorporate changes made in "old stable" since it does not benefit anyone but old/interim maintainer who wanted to clean up duplicate contents and difficult-to-update listing for credits, further complicated by hardcoded text in GUI.

Besides the hardcoding issue, other issues created were all issues that @clearkimura had noticed one after another, while figuring out how to remove the hardcoding part in GUI.


> where is the development plan of official fork?

There was no information/plan of whether official fork is going to resolve such duplicates, and despite fork maintainer was mentioned at least several times (clearkimura#70, clearkimura#127, clearkimura#130) whilst doing trivial clean up, no feedback/warning to prevent further trivial changes in "old stable" between August 2016 until recently.


**Pre-misunderstood option**

Back then, the best option was to transfer repo to the next contributor. @clearkimura was naive and had choosen "the path of least resistance"; he should have listened to the opinion of original developer, who had already suggested to transfer repo but it was not inline with preference of fork maintainer.

Even after "option D" was agreed, the best expected result was fork development takes place more rapid, which will make "old stable" redundant anyways (just like LibreOffice became successful fork, after leaving off OpenOffice). Unfortunately, that didn't happen.

**Post-misunderstood option**

Although it feels not right to stop working on "old stable" now, damage has been done on both sides. As such, to prevent further misunderstanding, it is better to take either one of three options:

A. Transfer repo of "old stable" to fork maintainer, preferably after renaming official fork to avoid lettercase conflict

B. Allow official fork to move on, then delete repo of "old stable" after making backup elsewhere

C. Allow "old stable" to move on until 4.2.0, then official fork can move on, then delete repo of "old stable" after making backup elsewhere

While fork maintainer has changed stance to prefer C., which is to support solving issues "old stable", @clearkimura personally wish for option A, so no more misunderstanding will occur later onwards.


@kamilion
Damage has been done on both sides. I have lost interest to do trivial clean up in "old stable". Therefore, I can't agree with option C. Would you rather choose option A or B?

**Comment by clearkimura** [comment]
@kamilion 
After thinking overnight, I have proceeded with option B.

> B. Allow official fork to move on, then delete repo of "old stable" after making backup elsewhere

That is, "old stable" repository shall be deleted all together, since almost everything has been cloned to fork already (except for issues, which are unwanted and irrelavant for fork anyway).

For one last time, I have merged a pull request (clearkimura#162) to fix essential issues in "old stable". No more commits in "old stable" following this.

I have decided to put grace period of 2 weeks that I had noted in README and commit history of "old stable". Then, this issue can be closed once "old stable" repository is removed.

I can be reached via @mentions on GitHub until then.

**Comment by kamilion** [comment]
Whoa; you can transfer the repo to me; I can just rename this one!
Deleting the repo will stop users from being forwarded and break the github history chain.

**Comment by kamilion** [comment]
@clearkimura okay, you can transfer the repo and all of it's issues and commit history to me, I've renamed my repo.

**Comment by clearkimura** [comment]
Preparing to transfer repository of "old stable" to fork maintainer.

Quoting from [this help page on GitHub](https://help.github.com/articles/about-repository-transfers/):

> Before you transfer a repository, keep these things in mind:
> 
> * When the current owner initiates the transfer, the new owner will receive an email giving the option to accept or reject the transfer. If the new owner doesn't accept the transfer within one day, it won't complete.
> * The target account must not have a repository with the same name, or a fork in the same network.
> * The original owner of the repository is added as a collaborator on the transferred repository. Other collaborators to the transferred repository remain intact.
> * Private forks can't be transferred.

@kamilion 
So renaming repository is mandatory (done). I'll need to add yours to collaborator of "old stable" before repository transfer could take place. Waiting for your accept.

**Comment by kamilion** [comment]
@clearkimura Collaboration invite accepted.

**Comment by clearkimura** [comment]
Transfer has failed, despite the fork repository has been renamed. I suppose the existence of fork itself already prevented transfer from happening. Attached screenshot as proof.

![transfer-repo-old-stable-failed](https://cloud.githubusercontent.com/assets/1223304/22417437/3928f0f6-e70f-11e6-83b5-ac647a91181c.png)

**Comment by clearkimura** [comment]
At this point, I believe option B was the best decision.

Quoting from [another help page on GitHub](https://help.github.com/articles/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility/):

> Deleting a public repository
> 
> When you delete a public repository, one of the existing public forks is chosen to be the new parent repository. All other repositories are forked off of this new parent and subsequent pull requests go to this new parent.

As yesterday, I have checked all forks listed in network members of "old stable" and none of them were up to date (closest fork was few commits ahead and 30 commits behind "old stable"). As today, there is a new fork created from official fork (probably the only one even with official fork at this time).

@kamilion 
In terms of up-to-date and hierarchy of network members, I think **yours official fork is the latest** and would be "the new parent" for all other forks. The "only loss" would be the hundreds of issues that were unwanted and irrelevant to official fork.

Above all, I don't see anything wrong with this result. Should there be any better option that you can think of, there is still some time until the grace period is over on Feb 11, 2017.

**Comment by clearkimura** [comment]
A quick clarification regarding "the new parent". According to [this recent post on webapps SE](http://webapps.stackexchange.com/q/86769), the following were revealed and made clear:

> Question:
> Which fork is marked as a main repository when the original one is deleted in GitHub?
> 
> Answer:
> Provided that the main repository is public, the oldest fork is selected to become the parent
> [...]
> > However, they original root repo owner can contact us beforehand to switch the root to whichever repo they'd like [...]

Here, "the oldest fork" probably means "the first fork" created from the original and *not* most up-to-date fork (my earlier expectation was wrong). Whichever fork becomes the new parent, link will be redirected there. Then again, I don't see anything wrong with this result.

Unless that is not desired, I'd have to contact GitHub support team beforehand (via email, I suppose). For now, I will just wait until the grace period ends.

**Comment by kamilion** [comment]
@clearkimura Alright, I've reviewed the issues that remain on this forked repository. 

@kamilion Two involve unicode errors, one is a 32bit/64bit packagename difference for the signed image (already fixed, which I'll further improve the behavior of), and the last one is adding a call to 'isohybrid' after build to add the ability to 'dd' the image to a USB stick directly.

**Comment by kamilion** [comment]
@clearkimura Alright, the last message sent me a notification with the remaining tasks from this repo.
I've pulled copies of all branches, archived them in tar.xz, and in about 5 minutes I'll remove the customizer-qt5 repo entirely.
